config/routes.rb
AjaxTodo::Application.routes.draw do
  resources :todo_items

  root :to => 'todo_items#new'

  

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :completed, :deleted, :due_at, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_items }
    end
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_item }
    end
  end

  # GET /todo_items/new
  # GET /todo_items/new.json
  def new
    @todo_item = TodoItem.new
    @todo_items_all = TodoItem.all

    @completed_items = TodoItem.where(:completed => true, :deleted => false)
    @todo_items = TodoItem.where(:completed => false, :deleted => false)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_item }
    end
  end

  # GET /todo_items/1/edit
  def edit
    @todo_item = TodoItem.find(params[:id])
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(params[:todo_item])

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render json: @todo_item, status: :created, location: @todo_item }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_items/1
  # PUT /todo_items/1.json
  def update
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      if @todo_item.update_attributes(params[:todo_item])
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ajax Todo List!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="wrapper">

    <h1>A Todo List, Built With Rails, jQuery, and AJAJ (Asynchronous Javascript and JSON)</h1>

    <%= yield %>

    <footer>
      <p>For the ice cream icon: <a target="_blank" href="http://creativecommons.org/licenses/by/3.0/">thanks to simon child</a>, from <a target="_blank" href="http://thenounproject.com/">The Noun Project</a></p>
      <p>For the egg icon: <a target="_blank" href="http://creativecommons.org/licenses/by/3.0/">thanks to Tom Glass, Jr.</a>, from <a target="_blank" href="http://thenounproject.com/">The Noun Project</a></p>
    </footer>

  </div>
</body>

</html>
<!-- 
    
    <section id="todo">
      <h2>To Do</h2>
      <ol>
        <li>Nothing to do!</li>
      </ol>
      <form action="#">
        <input type="text" name="new-todo" id="newTodo" placeholder="Add a new todo item...">
        <button type="submit">Add</button>
      </form>
    </section>
    <section id="completed">
      <h2>Completed!</h2>
      <ol>
        <li>Nothing completed.</li>
      </ol>
      <p>(You deserve an ice cream cone for each of these!)</p>
    </section>
 -->

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Enter a new todo item" %>
    <%= f.submit("Add") %>
  </div>
  <!-- <div class="field">
    <%= f.label :due_at %><br />
    <%= f.datetime_select :due_at %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div> -->
<!--   <div class="actions">
    <%= f.submit %>
  </div> -->
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due at</th>
    <th>Completed</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.name %></td>
    <td><%= todo_item.due_at %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.deleted %></td>
    <td><%= link_to 'Show', todo_item %></td>
    <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
    <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<%= render 'form' %>

<section id="todo">
  <h2>To Do</h2>
  <ol>
    <% if @todo_items.empty? && false #never show this, at least for now %>
      <li>Nothing to do!</li>
    <% else %>
      <% @todo_items.each do |todo_item| %>
        <li data-id="<%= todo_item.id %>">
          <input type="checkbox"><span><%= todo_item.name %></span>
          <button>Delete</button>
        </li>
      <% end %>
    <% end %>
  </ol>
</section>
<section id="completed">
  <h2>Completed!</h2>
  <ol>
    <% @completed_items.each do |todo_item| %>
      <li data-id="<%= todo_item.id %>">
        <input type="checkbox" checked="checked"><span><%= todo_item.name %></span>
        <button>Delete</button>
      </li>
    <% end %>
  </ol>
  <p>(You deserve an ice cream cone for each of these!)</p>
</section>

<!-- 
<table>
  <tr>
    <th>Name</th>
    <th>Due at</th>
    <th>Completed</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.name %></td>
    <td><%= todo_item.due_at %></td>
    <td><%= todo_item.completed %></td>
    <td><%= todo_item.deleted %></td>
    <td><%= link_to 'Show', todo_item %></td>
    <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
    <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
 -->
<!-- 
<br />

<%= link_to 'New Todo item', new_todo_item_path %>


<%= link_to 'Back', todo_items_path %>
 -->

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo_item.name %>
</p>

<p>
  <b>Due at:</b>
  <%= @todo_item.due_at %>
</p>

<p>
  <b>Completed:</b>
  <%= @todo_item.completed %>
</p>

<p>
  <b>Deleted:</b>
  <%= @todo_item.deleted %>
</p>


<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>